package salesforce.utils;

public enum EnvironmentFieldsEnum {
    BASE_URL,
    SALESFORCE_USERNAME,
    SALESFORCE_PASSWORD,
    SALESFORCE_TOKEN,
    SALESFORCE_CLIENT_ID,
    SALESFORCE_CLIENT_SECRET,
    ADMIN_URL,
    BASE_URL_CLASSIC
}
